name: 'squads-multisig-program-upgrade'
description: 'Get started with Container actions'
author: '0x'
inputs: 
  rpc_node:
    description: 'Solana rpc node to use. Eg. https://api.devnet.solana.com'
    default: 'https://api.devnet.solana.com'
  keypair_json:
    description: 'JSON string representation of your solana keypair. 
    Eg. [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
branding:
  icon: 'award'
  color: 'green'
